plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':app')
    implementation project(':admin')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    runtimeOnly 'com.mysql:mysql-connector-j'

    // Flyway
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'

}

tasks.named('bootJar') {
    enabled = true

    from(project(':admin').file('src/main/resources/templates/admin')) {
        into 'templates/admin'
    }

    dependsOn project(':app').tasks.named('generateSwaggerUISample')
    from("${project(':app').tasks.generateSwaggerUISample.outputDir}") {
        into 'BOOT-INF/classes/static/swagger-ui'
    }
}
