# common-dev config
spring.config.import=optional:file:./config/application-common-dev.properties

# S3
aws.s3.bucket=${S3_BUCKET}
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-part-count=30
