SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE member;
TRUNCATE TABLE hearit;
TRUNCATE TABLE bookmark;
TRUNCATE TABLE category;
TRUNCATE TABLE hearit_keyword;
TRUNCATE TABLE keyword;
SET FOREIGN_KEY_CHECKS = 1;
