CREATE TABLE advertisement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(500) NOT NULL COMMENT 'S3에 저장된 이미지 URL',
    link_url VARCHAR(500) NOT NULL COMMENT '광고 링크',
    title VARCHAR(200) NOT NULL COMMENT '광고 제목',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='광고';
