spring.application.name=hEARit
spring.profiles.active=dev

# JPA Auditing
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
server.tomcat.max-part-count=30

# Spring Actuator - Health Check
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
spring.datasource.hikari.pool-name=HikariPool-1
