# secret import
spring.config.import=optional:file:../.env[.properties]

# DataSource
# ==================================
# Master (Primary)
# ==================================
spring.datasource.master.jdbc-url=jdbc:mysql://${MYSQL_WRITER_ENDPOINT}:${TEST_MYSQL_PORT}/${MYSQL_DATABASE}?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.master.username=root
spring.datasource.master.password=${MYSQL_TEST_USER_PASSWORD}
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================================
# Replica
# ==================================
spring.datasource.replica.jdbc-url=jdbc:mysql://${MYSQL_WRITER_ENDPOINT}:${TEST_MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.replica.username=root
spring.datasource.replica.password=${MYSQL_TEST_USER_PASSWORD}
spring.datasource.replica.driver-class-name=com.mysql.cj.jdbc.Driver

# Dev-JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# kakao base-url
kakao.user-info.base-url=https://kapi.kakao.com
kakao.user-info.connectTimeout=2000
kakao.user-info.readTimeout=3000

# Jwt
jwt.secret=test-example-jwt-secret-test-example-jwt-secret
jwt.access-token.expiration=100000
jwt.refresh-token.expiration=600000

# user-default-image
hearit.profile.default-image-url=http://hearit.o-r.kr/images/default-profile.jpg

# S3
aws.region=fake-region
aws.s3.bucket.url=https://test.com
aws.s3.bucket=fake-bucket
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-part-count=30

## Flyaway
spring.flyway.url=jdbc:mysql://localhost:13307/hearit_db?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.flyway.user=root
spring.flyway.password=root

app.version=test
