SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE member;
TRUNCATE TABLE hearit;
TRUNCATE TABLE bookmark;
TRUNCATE TABLE category;
TRUNCATE TABLE hearit_keyword;
TRUNCATE TABLE keyword;
TRUNCATE TABLE admin;
TRUNCATE TABLE refresh_token;
TRUNCATE TABLE recommend_hearit;
TRUNCATE TABLE hearit_source;
TRUNCATE TABLE explore_score;
TRUNCATE TABLE playing_history;
SET FOREIGN_KEY_CHECKS = 1;

-- AUTO_INCREMENT 리셋 추가
ALTER TABLE member AUTO_INCREMENT = 1;
ALTER TABLE hearit AUTO_INCREMENT = 1;
ALTER TABLE category AUTO_INCREMENT = 1;
ALTER TABLE playing_history AUTO_INCREMENT = 1;
ALTER TABLE bookmark AUTO_INCREMENT = 1;
ALTER TABLE keyword AUTO_INCREMENT = 1;
ALTER TABLE admin AUTO_INCREMENT = 1;
ALTER TABLE refresh_token AUTO_INCREMENT = 1;
ALTER TABLE recommend_hearit AUTO_INCREMENT = 1;
ALTER TABLE hearit_source AUTO_INCREMENT = 1;
ALTER TABLE explore_score AUTO_INCREMENT = 1;
