name: Hearit Android CI

on:
  pull_request:
    branches: [ "main", "develop-an", "release", "develop", "temp-ci-1" ]
    paths:
      - 'android/**'

env:
  KEYSTORE_JKS: ${{ secrets.KEYSTORE_BASE64 }}
  KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: android
        
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Local Properties
        env:
          BASE_URL: ${{secrets.BASE_URL}}
        run:
          echo base.url=\"$_BASE_URL\" >> ./local.properties
      
      - name: Get Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
        run:
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json

      - name: Create KeyStore File and Properties
        run: |
          mkdir -p ./app/signing
          echo "$KEYSTORE_JKS" | base64 --decode > ./app/signing/hearit_keystore.jks
          echo "$KEYSTORE_PROPERTIES" > ./keystore.properties

      # 1. AAB 빌드
      # - name: Build AAB
      #   run: ./gradlew clean bundleRelease
      
      # 2. APK 빌드
      # - name: Build APK
      #   run: ./gradlew assembleRelease

      # Upload AAB
      # - name: Upload a Build AAB Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     # Artifact name
      #     name: hearit-release-aab
      #     # A file, directory or wildcard pattern that describes what to upload
      #     path: android/app/build/outputs/bundle/release/app-release.aab
      #     retention-days: 14

      # Upload APK
      - name: Upload a Build APK Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: hearit-release-apk
          # A file, directory or wildcard pattern that describes what to upload
          path: android/app/build/outputs/apk/release/hEARit-release.apk
          retention-days: 14

      - name: Debug Secret Content
        run: |
          echo "${{ secrets.CREDENTIAL_FILE_CONTENT }}" | head -c 50

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: hearit-test
          releaseNotesFile: android/app/release_note.txt
          file: android/app/build/outputs/apk/release/hEARit-release.apk

      # - name: Run ktlint Check
      #   run: ./gradlew ktlintCheck
        
      # - name: Run Unit Tests
      #   run: ./gradlew test
        
      - name: If Success, Send notification on Slack
        if: ${{success()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#60E0C5'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Hearit PR Checker have passed ✅'
          MSG_MINIMAL: true
          SLACK_USERNAME: Hearit Android
          SLACK_MESSAGE: 'Hearit Android PR Check Success 🎉'
          
      - name: If Fail, Send notification on Slack
        if: ${{failure()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Hearit PR Checker have failed ❌'
          MSG_MINIMAL: true
          SLACK_USERNAME: Hearit Android
          SLACK_MESSAGE: 'Hearit Android PR Check Failure - Should Check Up'
