name: Hearit Android CI

on:
  pull_request:
    branches: [ "main", "develop-an" ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: android
        
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Local Properties
        env:
          BASE_URL: ${{secrets.BASE_URL}}
        run:
          echo base.url=\"$_BASE_URL\" >> ./local.properties
        
      - name: Get Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
        run:
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
          
      - name: Clean Project
        run: ./gradlew clean
        
      - name: Run ktlint Check
        run: ./gradlew ktlintCheck
        
      - name: Run Unit Tests
        run: ./gradlew test
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: If Success, Send notification on Slack
        if: ${{success()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#60E0C5'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Hearit PR Checker have passed ✅'
          MSG_MINIMAL: true
          SLACK_USERNAME: Hearit Android
          SLACK_MESSAGE: 'Hearit Android PR Check Success 🎉'
          
      - name: If Fail, Send notification on Slack
        if: ${{failure()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Hearit PR Checker have failed ❌'
          MSG_MINIMAL: true
          SLACK_USERNAME: Hearit Android
          SLACK_MESSAGE: 'Hearit Android PR Check Failure - Should Check Up'
