name: Backend CI

on:
  push:
    branches: [ "main", "develop-be", "chore/#19-ci-cd" ]
  pull_request:
    branches: [ "main", "develop-be", "chore/#19-ci-cd" ]
# 테스트를 위한 path 제거
#    paths:
#      - 'backend/**'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Build with Gradle
        run: ./gradlew build
