name: Backend CI

on:
  push:
    branches: [ "develop-be" ]
  pull_request:
    branches: [ "develop-be" ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    defaults:
          run:
            working-directory: backend
            
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hearit_db
        ports:
          - 13307:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MYSQL_ROOT_PASSWORD: root
      TEST_MYSQL_PORT: 13307
      db.mysql.host: localhost:13307

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew test
      
      - name: Build with Gradle
        run: ./gradlew build -x test
