package com.onair.hearit.core.domain.exception;

public enum DomainErrorCode {
    BOOKMARK_DOMAIN_ERROR,
    CATEGORY_DOMAIN_ERROR,
    EXPLORE_SCORE_DOMAIN_ERROR,
    HEARIT_DOMAIN_ERROR,
    HEARIT_KEYWORD_DOMAIN_ERROR,
    KEYWORD_DOMAIN_ERROR,
    MEMBER_DOMAIN_ERROR,
    PLAYING_HISTORY_DOMAIN_ERROR,
    RECOMMEND_HEARIT_DOMAIN_ERROR,
    USERINFO_DOMAIN_ERROR,
    REFRESH_TOKEN_DOMAIN_ERROR,
    REACTION_DOMAIN_ERROR,
    ADVERTISEMENT_DOMAIN_ERROR,
    HEARIT_CLUSTER_DOMAIN_ERROR,
    ;
}
